Repository ConnorRichmond/adopt-dont-shop-7, pull requests merged in 2023-07, with the labels that each got.

#30 User story 1
  app/controllers/adoption_apps_controller.rb
  app/models/adoption_app.rb
  app/views/application/show.html.erb
  config/routes.rb
  db/migrate/20230713230625_create_adoption_apps.rb
  db/schema.rb
  db/seeds.rb
  spec/features/adoption apps/show_spec.rb
  spec/rails_helper.rb
Labels: PR

#32 Edit seeds to reflect renaming
  db/seeds.rb
Labels: bug, PR

#33 Development db seeds creation
  db/seeds.rb
  spec/features/adoption apps/show_spec.rb
  spec/spec_helper.rb
Labels: enhancement

#35 styling: Add page breaks
  app/views/pets/index.html.erb
Labels: optional

#36 User story 3
  app/controllers/adoption_apps_controller.rb
  app/models/adoption_app.rb
  app/views/application/new.html.erb
  spec/features/adoption apps/new_spec.rb
Labels: enhancement, mandatory, PR

#37 4 searching for pets for an application
  app/controllers/adoption_apps_controller.rb
  app/models/adoption_app.rb
  app/views/adoption_apps/search_pets.html.erb
  app/views/application/show.html.erb
  config/routes.rb
  spec/features/adoption apps/new_spec.rb
  spec/features/adoption apps/show_spec.rb
Labels: enhancement

#38 5 add a pet to an application
  app/controllers/adoption_apps_controller.rb
  app/models/adoption_app.rb
  app/models/pet.rb
  app/views/application/show.html.erb
  config/routes.rb
  db/migrate/20230716180254_create_join_table_adoption_app_pet.rb
  db/schema.rb
  spec/features/adoption apps/show_spec.rb
  spec/spec_helper.rb
Labels: mandatory, PR

#39 6 submit an application
  app/controllers/adoption_apps_controller.rb
  app/models/adoption_app.rb
  app/models/adoption_app_pet.rb
  app/models/pet.rb
  app/views/application/show.html.erb
  config/routes.rb
  db/migrate/20230716180254_create_join_table_adoption_app_pet.rb
  db/migrate/20230717161744_create_adoption_app_pets.rb
  db/schema.rb
  spec/features/adoption apps/show_spec.rb
Labels: enhancement

#41 Add matching for partial searches for pet search.
  app/controllers/adoption_apps_controller.rb
  db/schema.rb
  spec/features/adoption apps/show_spec.rb
Labels: documentation, enhancement

#42 Clarification on tests for #9
  spec/features/adoption apps/show_spec.rb
Labels: documentation

#43 Complete user story 10
  app/controllers/admin/shelters_controller.rb
  app/models/admin/shelter.rb
  app/views/admin/shelters/index.html.erb
  config/routes.rb
  db/schema.rb
  spec/admin/shelters/index_spec.rb
Labels: enhancement, mandatory, PR

#44 test: Add model tests
  app/models/adoption_app.rb
  spec/models/adoption_app_pet_spec.rb
  spec/models/adoption_app_spec.rb
  spec/models/pet_spec.rb
Labels: mandatory, PR

#45 11 shelters with pending applications
  app/controllers/admin/shelters_controller.rb
  app/controllers/adoption_apps_controller.rb
  app/models/adoption_app.rb
  app/views/admin/shelters/index.html.erb
  spec/admin/shelters/index_spec.rb
  spec/features/adoption apps/show_spec.rb
Labels: deployment, PR

#46 12 approving a pet for adoption
  app/controllers/admin/adoption_apps_controller.rb
  app/controllers/adoption_apps_controller.rb
  app/views/admin/adoption_apps/show.html.erb
  config/routes.rb
  spec/admin/applications/show_spec.rb
  spec/admin/shelters/index_spec.rb
Labels: enhancement, mandatory, PR

#47 Update buttons to allow rejection
  app/controllers/admin/adoption_apps_controller.rb
  app/views/admin/adoption_apps/show.html.erb
  config/routes.rb
  db/migrate/20230719214551_add_status_to_adoption_app_pets.rb
  db/schema.rb
  spec/admin/applications/show_spec.rb
  spec/features/adoption apps/show_spec.rb
Labels: enhancement

#48 Change status change from app status to pet status changes. Not affec…
  app/controllers/admin/adoption_apps_controller.rb
  app/models/adoption_app_pet.rb
  app/views/admin/adoption_apps/show.html.erb
  config/routes.rb
  db/migrate/20230719214551_add_status_to_adoption_app_pets.rb
  db/schema.rb
Labels: enhancement

#50 Add partials
  app/views/shelters/_form.html.erb
  app/views/shelters/edit.html.erb
  app/views/shelters/new.html.erb
  db/migrate/20230719214225_add_status_to_adoption_app_pets.rb
Labels: PR
